/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#191a2b",
        "primary-container": "#1c1b1b",
        "surface-container-highest": "#e2e3e1",
        "secondary": "#5146d0",
        "primary-fixed": "#e5e2e1",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#f9f9f7",
        "on-error": "#ffffff",
        "surface-dim": "#dadad8",
        "on-surface": "#1a1c1b",
        "inverse-surface": "#2f3130",
        "surface-container-high": "#e8e8e6",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary": "#ffffff",
        "state-success": "#42C77A",
        "tertiary": "#000000",
        "text-secondary": "#6F6F73",
        "on-primary-fixed-variant": "#474646",
        "state-danger": "#E85D5D",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9f7",
        "error": "#ba1a1a",
        "orb-gradient-start": "#8D8BFF",
        "surface": "#FFFFFF",
        "text-primary": "#111111",
        "inverse-on-surface": "#f1f1ef",
        "surface-container-low": "#f4f4f2",
        "surface-tint": "#5f5e5e",
        "text-muted": "#9A9A9F",
        "on-surface-variant": "#444748",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed-variant": "#3b2bba",
        "outline": "#747878",
        "surface-container": "#eeeeec",
        "border-subtle": "#E8E8E8",
        "orb-gradient-end": "#6D72E8",
        "orb-gradient-mid": "#C9C8FF",
        "on-primary-container": "#858383",
        "surface-dark": "#171717",
        "secondary-fixed": "#e3dfff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#c5c4dc",
        "on-tertiary-fixed-variant": "#444558",
        "surface-variant": "#e2e3e1",
        "primary": "#000000",
        "on-background": "#1a1c1b",
        "tertiary-fixed": "#e1e0f8",
        "on-secondary-fixed": "#120068",
        "on-primary": "#ffffff",
        "secondary-container": "#6a61eb",
        "tertiary-container": "#191a2b",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c4c0ff",
        "on-tertiary-container": "#828297",
        "inverse-primary": "#c8c6c5"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "gutter-tablet": "1.5rem",
        "margin": "1.25rem",
        "space-md": "1rem"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "caption": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "caption": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-hero-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
